-- ====================================================================
-- TradeOps - Schema do Banco de Dados Supabase
-- ====================================================================
-- Copie todo este codigo, abra o Supabase, clique em "SQL Editor"
-- no menu lateral esquerdo, cole e clique no botao "Run" (Executar).
-- ====================================================================

create table if not exists public.tradeops_metrics (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  vps_id text,
  account_login text,
  broker text,
  currency text default 'USD',
  balance numeric,
  equity numeric,
  today_pnl numeric,
  today_deals int,
  raw_data jsonb
);

-- Indice para buscas rapidas por conta e data
create index if not exists idx_tradeops_account_created on public.tradeops_metrics(account_login, created_at desc);

-- Politicas de seguranca (Row Level Security) para permitir leitura e escrita com a chave anon
alter table public.tradeops_metrics enable row level security;

drop policy if exists "Permitir insercao anonima" on public.tradeops_metrics;
create policy "Permitir insercao anonima"
on public.tradeops_metrics for insert
to anon
with check (true);

drop policy if exists "Permitir leitura anonima" on public.tradeops_metrics;
create policy "Permitir leitura anonima"
on public.tradeops_metrics for select
to anon
using (true);
